lombok.accessors.chain = true

spring.datasource.url=jdbc:postgresql://endereco_aqui/db_aqui
spring.datasource.username=usuario aqui
spring.datasource.password=senha aqui
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=postgresql

spring.application.name=Emprestimos v1
server.port=8080
